name: New vulnerability for database
description: File a new vulnerability.
title: "x/vulndb: Go vuln report for <your package name>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a Go vulnerability!
  - type: input
    id: module
    attributes:
      label: Module
      description: What is the module containing this vulnerability?
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: What is the package containing this vulnerability?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the Go vulnerability.
    validations:
      required: true
  - type: input
    id: introduced
    attributes:
      label: Introduced Version(s)
      description: What version was the vulnerabiltiy introduced?
    validations:
      required: false
  - type: input
    id: fixed
    attributes:
      label: Fixed Version(s)
      description: What version was the vulnerabiltiy fixed?
    validations:
      required: false
  - type: input
    id: cve
    attributes:
      label: CVE
      description: If there is an existing CVE ID, type it below.
    validations:
      required: false
  - type: input
    id: commit
    attributes:
      label: Commit
      description: |
        Include the commit where this vulnerability was fixed.

        If more than one commit is relevant, put the latest one here, and
        include the other under additional references.
    validations:
      required: false
  - type: input
    id: pr
    attributes:
      label: PR
      description: |
        Include the PR where this vulnerability was fixed.

        If more than one PR is relevant, put the latest one here, and
        include the other under additional references.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: Additional References
      description: Additional references for this vulnerability.
      placeholder: |
       Please include one reference/URL per line. For example,
       https://example.com/my/package/another/commit
       https://example.com/my/package/fix/announcement/email
    validations:
      required: false
  - type: textarea
    id: symbols
    attributes:
      label: Symbols
      description: Include package symbols affected by this vulnerability.
      placeholder: |
       Please include one symbol per line. For example,
       NewSymbol
       anotherSymbol
    validations:
      required: true
  - type: input
    id: credit
    attributes:
      label: Credit
      description: How would you like to be credited for this report?
    validations:
      required: false
